service_name: "validator"

Postgres:
  host: "localhost"
  port: "5432"
  user: "habrpguser"
  password: "pgpwd4habr"
  DBName: "habrdb"
  sslMode: "allow"

Server: #http
  host: "0.0.0.0"
  port: "3000"

smtp:
  host: "smtp.example.com"
  port: 587
  username: "your_email@example.com"
  password: "your_email_password"
  from: "your_email@example.com"

